# Generated by Django 2.2.7 on 2020-03-01 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='TourGuide',
            new_name='tourGuide',
        ),
    ]
