# Generated by Django 2.2.7 on 2020-02-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tourguide_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourguide',
            name='gender',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
