# Generated by Django 2.2.7 on 2020-02-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tourguide_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourguide',
            name='gender',
        ),
        migrations.AddField(
            model_name='tourguide',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
